### ISSUE TITLE
Uncaught DOMException: Failed to execute 'postMessage' on 'Window' #1879 

### ISSUE THREAD

**Issue by jbaxleyiii** [apollographql/apollo-client-devtools#64] opened 2017-07-17 14:16 UTC
From [AC](https://github.com/apollographql/apollo-client/issues/1879)

* could be related to [#1871](https://github.com/apollographql/apollo-client/issues/1871)

I have afterware on my apollo client to handle errors in my app. In order to check the server's response status I have to clone the response. It was working fine until suddenly (chrome update?) I started getting this message:
`DOMException: Failed to execute 'postMessage' on 'Window': Error: Network request failed with status 401 - "Unauthorized" could not be cloned.`
(the error is the response from the server).

To replicate, create an afterware that clones the response from the server.

Thanks!

**Comment by ramyanaga** [comment] 2017-07-17 17:08
Are you trying to post objects that are not Json-serializable? If so, this is the same issue as #58

**Comment by stubailo** [comment] 2017-07-18 17:23
Ah! Maybe this error has to do with errors being displayed in the dev tools?

**Comment by tnrich** [comment] 2017-07-21 19:08
Hitting this error as well. Does anyone have an idea why having an afterware with `response.clone() `  would be causing this to occur? I don't follow the logic there. Thanks!


```
VM146910:13 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': function xhrAdapter(config) {
  return new Promise(function dispatchXhrRequest(resolve, reject) {
    var reque...<omitted>...
} could not be cloned.
    at ApolloClient.hookLogger [as devToolsHookCb] (<anonymous>:13:12)
    at Object.dispatch (http://localhost:4000/static/js/bundle.js:133366:31)
    at dispatch (<anonymous>:2:1620)
...
```

**Comment by ramyanaga** [comment] 2017-07-24 17:28
@tnrich The breaking is in the hookLogger function defined in hook.js; its because chrome's postMessage function can't handle non-serializable objects. (I think)

**Comment by tnrich** [comment] 2017-07-24 17:47
@ramyanaga , thanks for the info!

Just to be clear, you're referring to this line in particular
```js
  const newStateData = {
      queries: logItem.state.queries,
      mutations: logItem.state.mutations,
      inspector: logItem.dataWithOptimisticResults
    }
    window.postMessage({ newStateData }, '*');
```
https://github.com/apollographql/apollo-client-devtools/blob/master/extension/hook.js#L27

That's what looked like the culprit might be to me as well. Is there something simple we could do to provide better feedback to the user? Perhaps something like:
```js
	try {
		JSON.stringify({newStateData})
	} catch (e) {
		return console.error('Uh oh, an error occurred when trying to serialize your apollo data:', e)
		//ideally we could make this message show up to the user so they know what is going wrong when serializing and can fix that error?
	}
    const newStateData = {
      queries: logItem.state.queries,
      mutations: logItem.state.mutations,
      inspector: logItem.dataWithOptimisticResults
    }
    window.postMessage({ newStateData }, '*');
    
```

**Comment by ramyanaga** [comment] 2017-07-24 18:53
@tnrich yep that's the line in particular. I'll try adding that line to give better error messages, but ideally I'd just stringify and unstringify the object within the app. 
Also, are you running the most recent version of the devtools (2.0.2)? I created a test app that uses response.clone() in afterware, but I don't seem to be having a problem

**Comment by tnrich** [comment] 2017-07-24 18:59
@ramyanaga , Yes I am using the latest version of the devtools, but I commented out the response.clone() line and I am still hitting this issue so it must be coming from something else. I was just confused initially and saw the `.clone() ` in the error message  and thought that my call was causing it.

**Comment by tnrich** [comment] 2017-07-24 19:01
@ramyanaga Also, what do you mean by 
>but ideally I'd just stringify and unstringify the object within the app.

Where in the app would you be doing that? In the apollo client itself? Or are you saying that as a user I could do a stringify/unstringify myself? 

Thanks!

**Comment by ramyanaga** [comment] 2017-07-24 19:16
@tnrich So the reason this error is occurring is because the user is including non-serializable objects in their queries (or mutations), which chrome's postMessage function cannot handle. For example, if the user passes in a date, postMesage will throw an error. I'd like to manually serialize this date object, then pass it through the message channels, then convert the data back into a date object before it is displayed on the devtools.

**Comment by tnrich** [comment] 2017-07-24 19:20
@ramyanaga Cool, thanks for the info!
Are non-serializable objects allowed in graphql queries? I, maybe incorrectly, thought that only json was allowed in graphql queries?

**Comment by peisenmann** [comment] 2017-07-26 14:46
@ramyanaga This is causing a fatal issue in my app whenever we get an error from our GraphQL server (An error where the HTTP response code is 200, but the response contains an `errors` property). As far as I can tell, the root of the issue is that ApolloClient dispatches [1] an instance of `Error` (since `ApolloError extends Error` [2]) to Redux. `Error` objects are not able to be sent via `window.postMessage` [3]. I don't believe there is anything I can do on the app side to prevent or solve this other than to not use the Apollo DevTools.

[1]: https://github.com/apollographql/apollo-client/blob/3b5045dfe74183fe060d2027e31317d890755b99/src/core/QueryManager.ts#L314
[2]: https://github.com/apollographql/apollo-client/blob/3b5045dfe74183fe060d2027e31317d890755b99/src/errors/ApolloError.ts#L33
[3]: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm

**Comment by ramyanaga** [comment] 2017-07-26 17:18
@peisenmann Thanks for the info. Can you reproduce the error for us or give us a way of reproducing it (using a site like Githunt). I'll look into it more and see if there's a way we can convert Errors to JSON before sending them through window.postMessage

**Comment by n1ru4l** [comment] 2017-08-09 08:07
Hey guys, I am also experiencing this issue when sending encoded json as a string.

Request payload:

```json
{
    "operationName": "submitQuestionnaire",
    "query": "mutation submitQuestionnaire($questionnaireId: Int!, $answers: [ParticipantAnswerInputType]!, $demographicAnswers: [DemographicParticipantAnswer]!) {\n  submitQuestionnaire(questionnaireId: $questionnaireId, answers: $answers, demographicAnswers: $demographicAnswers)\n}\n",
    "variables": {
        "answers": [
            {
                "questionId": 1,
                "timeout": false,
                "value": "1"
            },
            {
                "questionId": 2,
                "timeout": false,
                "value": "1"
            },
            {
                "questionId": 3,
                "timeout": false,
                "value": "2"
            },
            {
                "questionId": 4,
                "timeout": false,
                "value": "1"
            },
            {
                "questionId": 5,
                "timeout": false,
                "value": "\"PLUS\""
            },
            {
                "questionId": 6,
                "timeout": false,
                "value": "\"MINUS\""
            },
            {
                "questionId": 7,
                "timeout": false,
                "value": "\"PLUS_PLUS\""
            },
            {
                "questionId": 8,
                "timeout": false,
                "value": "\"MINUS_MINUS\""
            },
            {
                "questionId": 9,
                "timeout": false,
                "value": "1"
            },
            {
                "questionId": 10,
                "timeout": false,
                "value": "2"
            },
            {
                "questionId": 11,
                "timeout": false,
                "value": "1"
            },
            {
                "questionId": 12,
                "timeout": false,
                "value": "2"
            },
            {
                "questionId": 13,
                "timeout": false,
                "value": "\"MINUS_MINUS\""
            },
            {
                "questionId": 14,
                "timeout": false,
                "value": "\"PLUS_PLUS\""
            },
            {
                "questionId": 15,
                "timeout": false,
                "value": "\"PLUS\""
            },
            {
                "questionId": 16,
                "timeout": false,
                "value": "\"MINUS\""
            }
        ],
        "demographicAnswers": [],
        "questionnaireId": 1
    }
}
```

Relevant types:

```graphql
type ParticipantAnswerInputType {
  questionId: Int!
  timeout: Boolean!
  value: String! # Processed with JSON.stringify
}

type DemographicParticipantAnswer {
  demographicElementId: Int!
  value: String! # Processed with JSON.stringify
}
```

The "JSON" field are stringified before so AFAI this should not have any custom behaviour. I will try to set up a reproduction repo.

**Comment by n1ru4l** [comment] 2017-08-09 09:01
The issue was a non-serializable array ([which was provided by Ember](https://www.emberjs.com/api/ember/2.14/classes/Ember.Array)). **I fixed the issue** by converting it to a "plain" array before passing it into the mutation.

**Comment by lobosan** [comment] 2017-08-29 18:48
Same here, this is my resolver with apollo server
```
signUp: async (parent, args, { models }) => {
      const user = args
      user.contrasena = await bcrypt.hash(user.contrasena, 12)
      try {
        const newUser = await new models.User(user).save()
        return newUser
      } catch (error) {
        if (error.message.includes('users.$cedula_1 dup key')) {
          throw new Error('La cédula ingresada ya está registrada')
        } else if (error.message.includes('users.$email_1 dup key')) {
          throw new Error('El email ingresado ya está registrado')
        } else {
          throw new Error(error.message)
        }
      }
    }
```

And this is the error I'm getting in the console when committing an action with vuex:
```
DOMException: Failed to execute 'postMessage' on 'Window': Error: GraphQL error: La cédula ingresada ya está registrada could not be cloned.
    at ApolloClient.hookLogger [as devToolsHookCb] (<anonymous>:20:14)
    at eval (webpack-internal:///242:250:27)
    at Object.eval [as dispatch] (webpack-internal:///110:23:16)
    at QueryManager.mutate (webpack-internal:///243:133:20)
    at ApolloClient.mutate (webpack-internal:///242:208:34)
    at signUp (webpack-internal:///260:72:75)
    at Array.wrappedActionHandler (webpack-internal:///613:603:15)
    at Store.dispatch (webpack-internal:///613:346:15)
    at Store.boundDispatch [as dispatch] (webpack-internal:///613:271:21)
    at eval (webpack-internal:///629:55:25)
VM4608:23 DOMException: Failed to execute 'postMessage' on 'Window': Error: GraphQL error: La cédula ingresada ya está registrada could not be cloned.
    at ApolloClient.hookLogger [as devToolsHookCb] (<anonymous>:20:14)
    at eval (webpack-internal:///242:250:27)
    at Object.eval [as dispatch] (webpack-internal:///110:23:16)
    at eval (webpack-internal:///243:154:33)
    at <anonymous>
index.js?e3b1:77 Error: GraphQL error: La cédula ingresada ya está registrada
    at new ApolloError (ApolloError.js?d743:34)
    at eval (QueryManager.js?2cbe:129)
    at <anonymous>
```

**Comment by matthewerwin** [comment] 2017-11-21 21:06
Guys, I found a solution! Disable Apollo-client-devtools and viola, no more junk spewed into the console...haha. But seriously, hugely annoying bug -- I'm disabling it until this is fixed.

**Comment by barbalex** [comment] 2017-11-27 11:36
Something similar happens to me without using an afterware: I get this error:

```bash
DOMException: Failed to execute 'postMessage' on 'Window': TypeError: Cannot add property nodes, object is not extensible could not be cloned.
```

...when using apollo-link-state as only addition:

```js
const httpLink = createHttpLink({ uri: 'http://localhost:5000/graphql' })
const client = new ApolloClient({
  link: concat(localStateLink, httpLink),
  cache: new InMemoryCache(),
})
```

And it only seems to happen in an (unsolved) case where apollo returns this error:

```bash
Network error: Cannot add property nodes, object is not extensible
```

Disabling devtools removes the DOMException but not the network error (that probably causes the DOMException ).

**Comment by loganpowell** [comment] 2018-01-18 23:43
Just getting plugged into this thread for updates on this issue, which I'm also experiencing.

**Comment by barbalex** [comment] 2018-01-18 23:58
@loganpowell there is a button on top right for that: Notifications: "unsuscribe" (it was named "subscribe" before your comment)

**Comment by loganpowell** [comment] 2018-01-19 00:40
@barbalex but then I couldn't get nice messages like yours

**Comment by justinanastos** [comment] 2019-02-08 19:26
I'm going to close this issue up because it hasn't seen any activity in over a year. If anyone is still seeing an issue, please re-open the issue. Thank you!

**Closed by justinanastos** 2019-02-08 19:26 UTC
