### ISSUE TITLE
Cache Doesn't Update on Page Reload

### ISSUE THREAD

**Issue by zebulonj** [apollographql/apollo-client-devtools#121] opened 2018-05-17 00:32 UTC
**Expected**: When the page is refreshed or reloaded, the Cache displayed in the developer tools should be refreshed to reflect the changed application state.

**Actual**: The Apollo developer continue to show the cache state when the Chrome developer tools were initially loaded, even when the page is refreshed and the cache-state (presumably) returns to the initial application state. The only way to get the correct cache state to display in the extension is to close Chrome developer tools, then re-open.

**Steps to reproduce**:
1. Open a web-app using Apollo Client in development mode (`NODE_ENV !== 'production'`).
2. After the application loads, open Chrome developer tools, navigate to the Apollo tab and confirm that the Cache is visible.
3. Interact with the application and observe the state of the cache change.
4. Refresh the page: **the cache state does not change**.

In my steps to reproduce, I've actually submitted a form the executed a mutation... the results of which intersected the watched queries and therefore updated the cache state. Before reloading the page, I went into the local database and deleted the added records, guaranteeing that the state on refresh should change (when the queries are re-executed). However, I still see the mutation results in the displayed cache (even though they no longer exist in the database and the Network tab confirms they are not returned by the re-executed queries).

**Comment by stellarhoof** [comment] 2018-06-08 16:28
@zebulonj For a faster workflow, right click on the apollo section in the devtools and reload the frame. Still this should be correctly handled by the apollo devtools.

**Comment by richtera** [comment] 2018-07-11 13:07
I can't figure out how to clear cache at all sometimes. Even closing and restarting the dev tools sometimes caches content which I know I don't have in my local cache. Is someone working on this? Somehow not useful if it shows old data.

**Comment by saostad** [comment] 2018-08-03 15:53
same problem here.
cache not update even after refresh the page

**Comment by gihrig** [comment] 2018-08-18 05:07
@stellarhoof's method works intermittently for me. When it fails I get a connection timeout with the message "We couldn't detect Apollo Client in your app!"

OS X 10.11.6
Chrome:  68.0.3440.106 (Official Build) (64-bit)

**Comment by knappsacks** [comment] 2018-09-17 18:50
There are a couple ways you can clear the cache more quickly:

(1) Chrome DevTools: on the application, select 'Local Storage' and the localhost env you're developing in. Then above the 'Key' column, you can 'clear' the cache.

(2) You can use client.resetStore() to refresh the cache or client.clearStore() to clear the cache within the componentWillMount Lifecycle Hook on your main app.

`async componentWillMount() {
    await client.resetStore();
  }`

https://www.apollographql.com/docs/react/api/apollo-client.html#ApolloClient.resetStore

**Comment by silentlight** [comment] 2018-10-18 19:46
No updates on this one?

I am using Apollo with Nextjs and I always see old data. I think I might go back to Redux if I cannot easily see what's in cache :/

**Comment by alessandrodeste** [comment] 2018-10-26 11:18
It's not the best solution, but waiting for the fix I'm just checking the state from the chrome console:

    > __APOLLO_CLIENT__.cache.data.data['Item:3066']

**Comment by realalexhomer** [comment] 2018-11-12 19:50
I know its kind of crappy but it was just pointed out to me that in Chrome you can right click in the dev tool and click "reload frame" and it will fix the issue of it getting stuck.

<img width="489" alt="screen shot 2018-11-12 at 2 50 05 pm" src="https://user-images.githubusercontent.com/9168961/48371605-4c9c7f00-e68a-11e8-8364-2dcdb7f00baf.png">

**Comment by BenChirlin** [comment] 2018-12-11 22:59
At the very least we could add a "refresh" button like most plugins have to trigger a data reload instead of reloading the entire inspector frame.

**Comment by justinanastos** [comment] 2019-02-11 17:07
I just joined the devtools project, thanks for the bug report. This is something we'll be looking at soon.

**Comment by justinanastos** [comment] 2019-02-11 21:34
Unless I'm mistaken, this is a duplicate of #108. I'm going to close this issue. If I'm mistaken, please ping me and I'll re-open this.

**Closed by justinanastos** 2019-02-11 21:34 UTC
Labels: duplicate

**Comment by richtera** [comment] 2019-02-12 14:36
@justinanastos Yes it's the same issue as far as I can see as well.

**Comment by Stefano1990** [comment] 2019-05-16 18:30
I wasted too much time on this.

**Comment by meebix** [comment] 2019-05-19 21:55
Any updates on this? This is a pretty big (bad) issue from a developer experience standpoint.
