### ISSUE TITLE
Explorer remains blank

### ISSUE THREAD

**Issue by maerzhase** [apollographql/apollo-client-devtools#866] opened 2022-05-01 10:03 UTC
No matter what I do the explorer tab remains blank. I happens on Brave, Chrome and Firefox freshly installed browser + plugin. Devtools can connect with the client. I do see the queries etc. but the Explorer remains blank.

<img width="1552" alt="Screenshot 2022-05-01 at 11 58 08" src="https://user-images.githubusercontent.com/1128485/166141044-90da726a-0fe0-45b8-ad0a-72f17cfa933f.png">

It all worked fine last week and it happend out of the blue. Nothing changed on my machine. It kindof seems similar to what #823 although i dont see the same failed network calls. The errors in the console seem to be only related to google tag manager being blocked... I disabled all content blockers...

<img width="832" alt="Screenshot 2022-05-01 at 12 00 03" src="https://user-images.githubusercontent.com/1128485/166141105-b09b76ad-d82f-4f6b-8d7b-b71ed5320c98.png">

**Intended outcome:**
Expect my queries via explorer.

**Actual outcome:**
Explorer remains blank, although queries are visible so devtools are connected.

**How to reproduce the issue:**
I am not sure how to reproduce it, but on my machine currently happens on all browsers 

**Desktop:**
 - OS: macOS big sur 11.5.2
 - Browser Brave 1.38.109, Firefox 99.0.1, Chrome 101.0.4951.41
 - Extension version 4.0

**Comment by maerzhase** [comment] 2022-05-01 10:17
When enforce "light-mode" at least I see a loading spinner that never finishes :-) 

<img width="883" alt="Screenshot 2022-05-01 at 12 16 53" src="https://user-images.githubusercontent.com/1128485/166141669-e9743b01-f1d6-42a0-925a-1bfa04f03cc9.png">

**Comment by pleochroite** [comment] 2022-05-02 15:10
Same on my machine since several days ago.
Apollo client devtools' explorer shows a loading spinner endlessly not only on my local graphql server but also on Space-X API and SWAPI. 
Queries/Mutations/Cache tabs seem to be ok, as they show intended contents such as active queries and cache content.
The local graphql server log recorded accepting IntrospectionQuery from the client.

- OS: MacOS Catalina 10.15.7
- Browser: Firefox 99.0.1, Chrome 100.0.4896.127
- Apollo client devtools: 4.0.0

**Comment by aserranom** [comment] 2022-05-02 16:01
Same here with:

- OS: MacOS Big Sur 11.4
- Browser: Brave V1.38.109
- Apollo client devtools: 4.0.0

**Comment by maerzhase** [comment] 2022-05-03 15:37
Since its a huge blocker on my end, I had to find a temporary fix: I installed the old version 3.0.5 and there the explorer worked....

**Comment by acapro** [comment] 2022-05-06 09:28
Same problem here, as a temp fix I downloaded the source code from the releases page (https://github.com/apollographql/apollo-client-devtools/releases/tag/v4.0.0) - then built it with npm and node v10 -> the process is the following:

1. npm install
2. npm run zip
3. unpack the zip file for chrome in the newly created dist folder
4. remove the apollo extention
5. make sure dev mode is on, the click load from unpacked
6. explorer is working again!

Or just be lazy and use this 😄  [chrome-apollo_client_devtools-4.0.0.zip](https://github.com/apollographql/apollo-client-devtools/files/8638982/chrome-apollo_client_devtools-4.0.0.zip)

**Comment by cheapsteak** [comment] 2022-06-28 15:52
I believe this was caused by a release that contained a bug with a missing handshake    

It's since been fixed, but possibly persists on old bundles    

Could you please try uninstalling and reinstalling the extension and clearing cache? 🙏

**Comment by jpvajda** [comment] 2022-09-20 18:47
We've decided to close this out as a re-installation seems to be the path to resolution.

**Closed by jpvajda** 2022-09-20 18:47 UTC
Labels: 🐞 bug, 🚨 high-priority
