### ISSUE TITLE
Apollo console doesn't appear sometimes

### ISSUE THREAD

**Issue by danielo515** [apollographql/apollo-client-devtools#589] opened 2021-06-03 15:08 UTC
I have the apollo dev-tools installed on chrome.
Sometimes the apollo dev tools appear the same way React components and Redux does, but many times it doesn't appear.
I don't know why, and it's very frustrating 

**Intended outcome:**

I expected the apollo console to always appear, even if it has to show an error

**Actual outcome:**

No apollo console

**How to reproduce the issue:**

I wish I know what causes this, but I have no idea

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser  Chrome
 - Browser version 90.0.4430.212
 - Extension version 3.0.5

**Comment by ajaypillay** [comment] 2021-06-07 08:17
I face the same issue as well.
OS: Fedora 32 64-bit
Browser: Chrome
Browser Version: Version 91.0.4472.77 (Official Build) (64-bit)
Extension Version: 3.0.5

Sometimes I can fix this by closing the entire Chrome Dev Tools and/or closing and opening a new tab and opening up the dev tools again, then the Apollo tab appears.

It's quite erratic and unfortunately I can't provide more information as I'm not able to accurately consistently reproduce it.

For now I close and reopen the tab/Chrome Dev Tools until the Apollo tab appears.

**Comment by oirodolfo** [comment] 2021-06-16 18:57
It's happening with me a lot, unfortunately... The Apollo tab doesn't even appear most of the time.

-----

- OS: macOS
- Browser: Chrome & Chrome Canary
- Browser version: 93.0.4544.0  (but it also happens in Chrome 90)
- Extension version 3.0.5

**Comment by floriancargoet** [comment] 2021-06-24 13:23
It's happening to me today…

**Comment by MurzNN** [comment] 2021-07-27 07:07
Same problem with Firefox and Chrome on Linux too :-(

**Comment by Nightbr** [comment] 2021-08-07 10:47
Same on Firefox and Chrome on Linux Mint (recently). And when the tabs Apollo is present, there is nothing in it (no cache, no active queries). 

Seems an update in Firefox & Chrome has broken the extension.

- Linux Mint 20.2 Uma base: Ubuntu 20.04 focal 
- Firefox 90.0.2 (64 bits)
- Chrome Version 92.0.4515.131 (Build officiel) (64 bits)

On Chrome I have an error:

`Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.`
- https://stackoverflow.com/questions/54619817/how-to-fix-unchecked-runtime-lasterror-could-not-establish-connection-receivi
- https://stackoverflow.com/questions/54181734/chrome-extension-message-passing-unchecked-runtime-lasterror-could-not-establi/54686484#54686484

Seems it needs a fix with the latest Browser version

**Comment by Nightbr** [comment] 2021-08-10 06:57
Try it on a Macbook Pro:

* Chrome Version 92.0.4515.131 (Build officiel) (x86_64)
* Firefox  90.0.2

Same issue. Not related to OS but really related to new browsers update.
Any chance an Apollo team member take a look at this, this Devtool is really useful to debug the Cache and Active Queries.

thanks for your help!

**Comment by hwillson** [comment] 2021-08-13 16:57
Thanks for the details everyone, and sorry for the delay. We're looking into this.

**Comment by austinbiggs** [comment] 2021-09-08 22:52
Any follow-up here? :)

**Comment by steezeburger** [comment] 2021-09-10 15:04
Mine never appears. In fact, I've had it installed for like a year and completely forgot I had it because I don't think I've ever actually seen it load once. I've tried lots of things and cannot get it to ever appear.

**Comment by Nightbr** [comment] 2021-09-10 16:33
is there a workaround to debug Apollo cache without the browser extension? If anyone has a solution it could be a great workaround until this is fixed.
thanks a lot :pray:

**Comment by awarrenlove** [comment] 2021-09-15 10:58
@Nightbr You should be able to see what's in the current client cache by looking at `window.__APOLLO_CLIENT__.cache.data.data`.

**Comment by Nightbr** [comment] 2021-09-15 11:47
@awarrenlove This is weird because this object is empty:
![image](https://user-images.githubusercontent.com/4228646/133427800-d05adc1c-7d83-41c6-a789-b185eb4ebce7.png)

**Comment by mikaelgramont** [comment] 2021-11-03 12:32
It sure would be nice to be able to use this extension, but every time I reach for it, it's nowhere to found in my developer tools.

**Comment by ViktorCoder** [comment] 2021-11-25 22:59
Fixed it by changing the settings of this extension (Site access)

**Comment by Richacinas** [comment] 2021-12-02 07:53
Same as @ViktorCoder. I allowed all sites on the Site Access settings (in Spanish here):

![image](https://user-images.githubusercontent.com/7046504/144380344-02cf37f5-a2f5-4dcc-8847-338d7938bd8e.png)

**Comment by davemeehan** [comment] 2021-12-13 16:44
Unfortunately none of these work-arounds have worked for me. Any update on this @hwillson?
Osx 12.0.1

Doesn't work:
Chrome: Version 96.0.4664.93 (Official Build) (x86_64)
Brave: Version 1.32.115 Chromium: 96.0.4664.93 (Official Build) (x86_64)

DOES work in Firefox: 94.0.1 (64-bit)

**Comment by trev125** [comment] 2022-03-02 23:54
> The issue still exists on Browser - Chrome Version 94.0.4606.81 (Official Build) (x86_64) OS - macOS Catalina Version 10.15.7
> 
> After some trial and error, a temporary fix that I found was to: Disable the extension -> Go back to the website -> Close DevTools -> Refresh the page -> Enable the extension -> Go back to the website -> Refresh the page -> Open DevTools to find the Apollo extension there

This is the only thing that has worked for me on MacOS and Firefox. Would love to not have to do that everytime though

**Comment by onpaws** [comment] 2022-04-08 12:19
Just happened to me again. This issue seems to have become worse with the v3 release.

I notice that the React extension by comparison seems pretty reliable at loading itself. I'm ignorant of web extension initialization context, but would like to suggest to whoever is maintaining this extension, there could be some useful lessons to glean there.

**Comment by Richacinas** [comment] 2022-04-08 15:27
The only thing that works for me 90% of the times is:
- close tab and open new one.
- load your website and wait a little bit until it is "still" (Apollo operations are done).
- F12 and check it out. The Apollo tab should appear this time.

**Comment by atapas** [comment] 2022-06-16 12:53
Doesn't work At All.

**Comment by SadmanYasar** [comment] 2022-10-02 04:21
Facing this exact issue. It shows up on the Apollo Studio but not on the React app. Tried the workarounds but did not work.

**Comment by sethc2** [comment] 2022-10-06 17:37
Also has recently stopped working for me and other engineers I work with on both chrome and firefox.

I am able to get it to work if I add `connectToDevTools: true` where I new up our `ApolloClient`, but previously `window.__APOLLO_CLIENT__` showed up without having to do this.

**Comment by juanlet** [comment] 2022-10-12 02:37
> Also has recently stopped working for me and other engineers I work with on both chrome and firefox.
> 
> I am able to get it to work if I add `connectToDevTools: true` where I new up our `ApolloClient`, but previously `window.__APOLLO_CLIENT__` showed up without having to do this.

That is the solution, in fact they added it in their docs

https://www.apollographql.com/docs/react/development-testing/developer-tooling/

[Configuration](https://www.apollographql.com/docs/react/development-testing/developer-tooling/#configuration)
While your app is in dev mode, the Apollo Client Devtools will appear as an "Apollo" tab in your web browser inspector. To enable the devtools in your app in production, pass connectToDevTools: true to the ApolloClient constructor in your app. Pass connectToDevTools: false if want to manually disable this functionality.

**Comment by hwillson** [comment] 2022-10-12 23:02
Hi all - this issue is being tracked in multiple places. See https://github.com/apollographql/apollo-client-devtools/issues/924#issuecomment-1276793942 for the latest update.

**Comment by alessbell** [comment] 2023-09-05 23:24
Hi all 👋 

Both the devtools and `@apollo/client` have put out recent releases with various improvements to the registration mechanism that should resolve this issue.

Please ensure you are running the devtools at version **4.1.5 or greater** and Apollo Client at version **3.8.3 or greater** so I'll close out this issue. Please create a new issue to report any other bugs you may encounter, thanks :)

**Closed by alessbell** 2023-09-05 23:24 UTC
Labels: 🐞 bug, 2021-09
