### ISSUE TITLE
Mutations crash devtools

### ISSUE THREAD

**Issue by redmerten** [apollographql/apollo-client-devtools#182] opened 2019-02-14 21:27 UTC
Tools crash on mutations click and cache click.

 Chrome 72.0.3626.109. 
React 16.8
  "apollo-cache-inmemory": "^1.4.2",
    "apollo-client": "^2.4.12",
    "apollo-link": "^1.2.6",
    "apollo-link-rest": "^0.7.0",
    "graphql": "^14.1.1",
    "graphql-anywhere": "^4.1.27",
    "graphql-tag": "^2.10.1",

**Comment by justinanastos** [comment] 2019-02-15 16:58
Thanks for the report! The cache but is a duplicate of #107 and was resolved in [v2.1.7](https://github.com/apollographql/apollo-client-devtools/releases/tag/v2.1.7).

The mutations bug I'm working on right now and hopefully will have released by EOD.

**Comment by justinanastos** [comment] 2019-02-15 21:12
Fixed in [v2.1.8](https://github.com/apollographql/apollo-client-devtools/releases/tag/v2.1.8)

**Closed by justinanastos** 2019-02-15 21:12 UTC
Labels: bug, critical, has-reproduction
