### ISSUE TITLE
TypeDef with new types breaks GraphiQL documentation

### ISSUE THREAD

**Issue by ChristianRuiz** [apollographql/apollo-client-devtools#259] opened 2020-05-12 10:00 UTC
We've got a @client array of alerts and two mutations to interact with it. It's working properly, but we'd like to take advantage of the type def to add the documentation to GraphiQL.

Using the following typeDef, breaks the documentation ("NO SCHEMA AVAILABLE"):

![image](https://user-images.githubusercontent.com/6180622/81670093-65385180-9447-11ea-9c0e-4b55ba9f75f5.png)

![image](https://user-images.githubusercontent.com/6180622/81670174-87ca6a80-9447-11ea-8fbc-21305fa41017.png)

Using a basic type like String instead of Alert, the documentation is showing properly, but it's not accurate with our implementation:

![image](https://user-images.githubusercontent.com/6180622/81670410-d8da5e80-9447-11ea-8ff7-9324bb210c74.png)

![image](https://user-images.githubusercontent.com/6180622/81670388-ceb86000-9447-11ea-8b1b-fcdab684e61d.png)

![image](https://user-images.githubusercontent.com/6180622/81670590-23f47180-9448-11ea-9b78-6fc126760d34.png)

We've decided to keep the TypeDef specified with our types, but not use it on the client constructor to avoid breaking the tool documentation, but it would be great to have it there.

**Comment by zicklag** [comment] 2020-11-18 21:08
I am having a similar issue in Firefox. I can't specify any `typeDefs` or the documentation shows empty. I was unable to determine whether or not it was due to custom type definitions. It didn't seem to work in any combination I tried.

**Comment by pptang** [comment] 2020-12-12 04:31
In my case, it results from the duplicate name as remote schema. After I change make the type name unique, it works!

<img width="654" alt="Screen Shot 2020-12-12 at 13 29 42" src="https://user-images.githubusercontent.com/9260102/101975202-1a511780-3c7e-11eb-9c20-a7e4ba5dc446.png">

**Comment by hwillson** [comment] 2021-03-28 19:14
A lot (almost all) of the codebase has changed in devtools 3.0. I'll close this off for now, but if you're still running into this issue and can provide a small runnable reproduction, we'll take a look. Thanks!

**Closed by hwillson** 2021-03-28 19:14 UTC
Labels: 🐞 bug
