### ISSUE TITLE
After install extension the message on the log still exist "Download the Apollo DevTools for a better development experience"

### ISSUE THREAD

**Issue by performautodev** [apollographql/apollo-client-devtools#890] opened 2022-06-03 14:28 UTC
**Intended outcome:**
After install extension the message on the log still exist "Download the Apollo DevTools for a better development experience"

**Actual outcome:**
I installed from "https://chrome.google.com/webstore/detail/apollo-client-devtools/jdkknkkbebbapilgoeccciglkfbmbnfm"
but the log still exist i rebooted my pc and clear cache the log still exist :
![image](https://user-images.githubusercontent.com/62381545/171869290-6a960fa8-bfc3-4579-8e03-cbc9baeb2c59.png)

**How to reproduce the issue:**
check my repo : https://github.com/performautodev/apollo-extension-bug-1

![image](https://user-images.githubusercontent.com/62381545/171874125-6a3a8262-621e-4183-97c1-8693a86f63ea.png)

**Versions**

System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.36)
  npmPackages:
    @apollo/client: 3.5.10 => 3.5.10

**Comment by performautodev** [comment] 2022-06-05 10:41
Hello,
any updates please, the message on devtools is ugly 😫

**Comment by jpvajda** [comment] 2022-06-27 23:29
@performautodev  sorry you are experience an issue here. I cloned your sample app repo and was able to run the extension in both Firefox and Chrome.  I noticed you were running this on 

`Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.36)`


I'm not 100% sure this extension will work on MS Edge. Would you mind running it on FireFox or Chrome on your windows machine?

<img width="1438" alt="Screen Shot 2022-06-27 at 5 29 16 PM" src="https://user-images.githubusercontent.com/1395158/176053624-09d9550e-8974-491a-a0ad-bd8d31c8ce64.png">

![Screen Shot 2022-06-27 at 5 29 27 PM](https://user-images.githubusercontent.com/1395158/176053627-22e649ce-09b0-4881-a481-ca54e85d41ab.png)

**Comment by nick4fake** [comment] 2023-01-11 20:32
@jpvajda exactly the same problem on latest Chrome

**Comment by kegi** [comment] 2023-02-07 18:54
Also having this on Firefox

**Comment by AndrejGajdos** [comment] 2023-02-20 08:54
+1

**Comment by jerelmiller** [comment] 2023-02-21 04:50
Hey all 👋 

I have also noticed this from time to time. Without looking into this too deeply yet, my guess is there is some kind of race condition that prevents dev tools and Apollo Client from properly connecting to each other on boot up. Unfortunately its intermittent, so its a bit difficult to track down. I definitely agree its a bit annoying and would love to get it fixed.

If anyone is inclined to dig in a bit further, a great starting place would be looking at the [`ApolloClient` constructor](https://github.com/apollographql/apollo-client/blob/52a9c8ea1ac08ee53fe1ddbd4ded899ea00a1f9f/src/core/ApolloClient.ts#L195-L221) and how it interacts with dev tools. Here we check for the presence of a [`__APOLLO_DEVTOOLS_GLOBAL_HOOK__`](https://github.com/apollographql/apollo-client/blob/52a9c8ea1ac08ee53fe1ddbd4ded899ea00a1f9f/src/core/ApolloClient.ts#L201) function set on `window`. If this is absent, you see the message. My guess is this is likely `undefined`, perhaps due to Apollo Dev Tools not loaded before the `ApolloClient` is initialized. Check for how this variable is used in the dev tools repo and how dev tools is loaded and my guess is you'll get closer to finding the issue.

If not, I'll try and look at this a bit closer after I've cleared through some of my current commits. Thanks for being patient with this annoyance!

**Comment by DamodarSojka** [comment] 2023-04-06 06:08
Maybe at least there is a way to disable this message like there is for the react dev tools: https://stackoverflow.com/questions/42196819/disable-hide-download-the-react-devtools

**Comment by joenap** [comment] 2023-04-23 15:37
Having the same issue

**Comment by jerelmiller** [comment] 2023-06-13 18:36
We definitely hear the +1s and will work to address this shortly after the Apollo Client v3.8 release (sometime in the next few weeks). This one has bugged me like crazy lately so I have a vested interest in seeing this problem go away 😆.

**Comment by lobsterkatie** [comment] 2023-06-21 22:39
Possibly related? 

https://github.com/apollographql/apollo-client/issues/1470

**Comment by Francesco146** [comment] 2023-08-29 08:44
not yet fixed on latest Chrome and Apollo

**Comment by alessbell** [comment] 2023-09-06 17:55
This should be fixed with devtools versions **4.1.5 and greater** and Apollo Client **3.8.3 and greater** (currently the version at `latest`).

Would you mind trying again, @Francesco146? We just released `3.8.3` yesterday. Thanks!

**Comment by Francesco146** [comment] 2023-09-07 09:58
@alessbell updated to `v.3.8.3` and can confirm that the issue is no longer reproducible. thank you

**Comment by alessbell** [comment] 2023-09-07 12:47
Thanks for confirming, @Francesco146! I'll close this issue out. Anyone experiencing any issues in the future should open a new issue. Thanks all!

**Closed** 2023-09-07 12:47 UTC
Labels: 🐞 bug
