### ISSUE TITLE
apollo devtools are taking a ton of cpu to run

### ISSUE THREAD

**Issue by tnrich** [apollographql/apollo-client-devtools#74] opened 2017-09-08 19:07 UTC
I have a fairly large app with many queries being made. When I have the apollo devtools enabled, I find that after a short bit, my computer fan starts working double and the chrome extension helper is using ~100% cpu. 

I'm not sure if this is related to the issue I tried to help fix https://github.com/apollographql/apollo-client-devtools/issues/28, or if it is related to something new. My browser doesn't fully crash like it used to, but it is clearly taking quite a bit of cpu and slowing everything down. 

Is anyone else seeing something similar. 

Thanks!

**Comment by stubailo** [comment] 2017-09-08 19:30
Well, it's good to see some improvement! But there is still a lot of opportunity to reduce CPU usage. Curious about the following:

Do you still see the issue if...

1. You don't open the dev tools panel at all
2. You open the dev tools, but stay on the GraphiQL page

**Comment by tnrich** [comment] 2017-09-08 20:02
Hey @stubailo, the issue occurs whether or not the apollo tool is the current tab or not. The chrome devtools DO need to be open for it to happen however. 

Hmm it looks like a lot has actually changed since I last looked at this. It is probably due to new changes then that stuff is slow again. 

Can you point me to the commit where this code got introduced? 
```
let backgroundPageConnection = chrome.runtime.connect({
      // sending tabId as name to make connection one-step process
      name: chrome.devtools.inspectedWindow.tabId.toString()
    });

    backgroundPageConnection.onMessage.addListener((logItem, sender) => {
```
And, is there anything buffering that connection listener from getting run many times. 

When I last looked at it there was an evalInPage getting run to get the query/mutation data, and putting a buffer on that evalInPage fixed things. So I assume it is probably the same issue with the new data fetch method (backgroundPageConnection).

Thoughts on that? 

Hopefully we can get this fixed!

**Comment by tnrich** [comment] 2017-09-08 20:14
Some other little things: 
This code appears to not be doing anything anymore: 
```
 componentWillUnmount() {
    clearTimeout(this._interval);
  }
```
https://github.com/apollographql/apollo-client-devtools/blob/master/app/components/Panel.js#L83

**Comment by tnrich** [comment] 2017-09-08 20:22
Hmm after putting some console logs in the new code, it looks like the `backgroundPageConnection.onMessage.addListener(` listener isn't getting called very often so that probably isn't the issue. I'll keep investigating!

**Comment by stubailo** [comment] 2017-09-08 21:26
Yeah the main change is that we now push events from the page instead of polling. Any information about what is taking up the CPU time would be much appreciated for sure!

**Comment by tnrich** [comment] 2017-09-09 03:15
@stubailo so I hit the high cpu usage again and it appears it only happens when I hit a debugger or error in my application code. When I have the apollo devtool enabled I hit ~130% cpu vs ~5% when it is disabled.

**Comment by harmon25** [comment] 2017-09-15 15:25
hmm when testing React 16 rc2 in a rather large react + apollo app - i was getting some unexplained browser crashes, like entire tab hanging/unresponsive with seemingly no errors. Could have been some other interaction between dependencies...

Had Apollo tools enabled the entire time, did not think it was the cause, but after seeing this issue and the symptoms - I.E fans spinning loud,  may have been it. Reverted back to 15.6 - but the timing could have also aligned with the changes to apollo devtools...

If i notice it again, will debug more and report back

**Comment by justinanastos** [comment] 2019-02-08 19:25
Thanks for reporting this issue @tnrich . I'm going to close it because it hasn't seen any activity in a while. If this is still an issue please re-open it!

**Closed by justinanastos** 2019-02-08 19:25 UTC
