### ISSUE TITLE
"TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))" at chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/backend.js:16:149258

### ISSUE THREAD

**Issue by eberridge** [apollographql/apollo-client-devtools#306] opened 2020-10-30 16:07 UTC
Uncaught exception when using dev tools with web sockets subscriptions. My page crashes only when Apollo dev tools is open.

Apollo Client Developer Tools version 2.3.2
Chrome browser, Version 86.0.4240.111 (Official Build) (64-bit)

**Exception details**
```
backend.js:16 Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at backend.js:16
    at Object.next (backend.js:16)
    at T (backend.js:16)
    at g (backend.js:16)
    at e.value (backend.js:16)
    at backend.js:16
    at Array.forEach (<anonymous>)
    at T (backend.js:16)
    at Object.next (backend.js:16)
    at i (backend.js:16)
    at backend.js:16
    at backend.js:16
    at Set.forEach (<anonymous>)
    at backend.js:16
    at Map.forEach (<anonymous>)
    at e.broadcastQueries (backend.js:16)
    at backend.js:16
    at Object.next (backend.js:16)
    at T (backend.js:16)
    at g (backend.js:16)
    at e.value (backend.js:16)
    at backend.js:16
    at Set.forEach (<anonymous>)
    at Object.next (backend.js:16)
    at notifySubscription (Observable.js:135)
    at onNotify (Observable.js:179)
    at SubscriptionObserver.next (Observable.js:235)
    at notifySubscription (Observable.js:135)
    at onNotify (Observable.js:179)
    at SubscriptionObserver.next (Observable.js:235)
    at httpLink.ts:142
```

**Using:**
```
    "@apollo/react-hooks": "^3.1.3",
    "apollo-cache-inmemory": "^1.6.5",
    "apollo-client": "2.6.8",
    "apollo-link-context": "^1.0.19",
    "apollo-link-http": "^1.5.16",
    "apollo-link-ws": "^1.0.20",
    "apollo-utilities": "^1.3.3",
    "subscriptions-transport-ws": "^0.9.18",
```

**Client httpLink configuration code:**
```
const generateContext = ({ headers, token, ...context }) => {
  return {
    headers: {
      ...headers,
      ...(token ? { authorization: `Bearer ${token}` } : {})
    },
    credentials: 'omit',
    ...context
  };
};

export const buildApolloClient = ({
  apiUrl,
  apiSubscriptionUrl,
  authProvider
}: {
  apiUrl: string;
  apiSubscriptionUrl: string;
  authProvider: MsalAuthProvider;
}) => {
  const httpLink = new HttpLink({ uri: apiUrl });
  const authLink = setContext((_, { headers, ...context }) => {
    if (authProvider?.getIdToken) {
      return authProvider.getIdToken().then((tok) => {
        const token = tok?.idToken?.rawIdToken;
        return generateContext({ headers, token, ...context });
      });
    }
    const token = localStorage.getItem('msal.idtoken');
    return generateContext({ headers, token, ...context });
  }).concat(httpLink);

  let link: ApolloLink;
  if (apiSubscriptionUrl) {
    const wsLink = new WebSocketLink({
      uri: apiSubscriptionUrl,
      options: {
        reconnect: true,
        connectionParams: () => ({
          // Doesn't support promise but HTTP authlink will keep localStorage token fresh
          token: localStorage.getItem('msal.idtoken')
        })
      }
    });
    link = split(
      // split based on operation type
      ({ query }) => {
        const definition = getMainDefinition(query);
        return definition.kind === 'OperationDefinition' && definition.operation === 'subscription';
      },
      wsLink,
      authLink
    );
  } else {
    link = authLink;
  }

  return new ApolloClient({
    link,
    cache: new InMemoryCache({
      addTypename: false // TODO review with HotChocolate if there is a fix for this
    })
  });
};
```

**Comment by eberridge** [comment] 2020-10-30 16:16
Full stack in case it is helpful:

```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
(anonymous function)
chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/backend.js:16:149258
next
chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/backend.js:16:149266
T
chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/backend.js:16:131789
g
chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/backend.js:16:132293
e.value
chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/backend.js:16:132846
(anonymous function)
chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/backend.js:16:158062
T
chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/backend.js:16:158031
next
chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/backend.js:16:157596
i
chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/backend.js:16:171407
(anonymous function)
chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/backend.js:16:172567
(anonymous function)
chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/backend.js:16:178044
(anonymous function)
chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/backend.js:16:178021
e.broadcastQueries
chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/backend.js:16:177972
(anonymous function)
chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/backend.js:16:179913
next
chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/backend.js:16:133960
T
chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/backend.js:16:131789
g
chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/backend.js:16:132293
e.value
chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/backend.js:16:132846
(anonymous function)
chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/backend.js:16:165647
next
chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/backend.js:16:165610
notifySubscription
c:/Repos/DesignHub/node_modules/zen-observable/lib/Observable.js:135
  132 | 
  133 | switch (type) {
  134 |   case 'next':
> 135 |     if (m) m.call(observer, value);
      | ^  136 |     break;
  137 | 
  138 |   case 'error':
View compiled
onNotify
c:/Repos/DesignHub/node_modules/zen-observable/lib/Observable.js:179
  176 |     return;
  177 |   }
  178 | 
> 179 |   notifySubscription(subscription, type, value);
  180 | }
  181 | 
  182 | var Subscription =
View compiled
SubscriptionObserver.next
c:/Repos/DesignHub/node_modules/zen-observable/lib/Observable.js:235
  232 | _createClass(SubscriptionObserver, [{
  233 |   key: "next",
  234 |   value: function next(value) {
> 235 |     onNotify(this._subscription, 'next', value);
      | ^  236 |   }
  237 | }, {
  238 |   key: "error",
View compiled
notifySubscription
c:/Repos/DesignHub/node_modules/zen-observable/lib/Observable.js:135
  132 | 
  133 | switch (type) {
  134 |   case 'next':
> 135 |     if (m) m.call(observer, value);
      | ^  136 |     break;
  137 | 
  138 |   case 'error':
View compiled
onNotify
c:/Repos/DesignHub/node_modules/zen-observable/lib/Observable.js:179
  176 |     return;
  177 |   }
  178 | 
> 179 |   notifySubscription(subscription, type, value);
  180 | }
  181 | 
  182 | var Subscription =
View compiled
SubscriptionObserver.next
c:/Repos/DesignHub/node_modules/zen-observable/lib/Observable.js:235
  232 | _createClass(SubscriptionObserver, [{
  233 |   key: "next",
  234 |   value: function next(value) {
> 235 |     onNotify(this._subscription, 'next', value);
      | ^  236 |   }
  237 | }, {
  238 |   key: "error",
View compiled
(anonymous function)
c:/Repos/src/httpLink.ts:142
  139 | .then(parseAndCheckHttpResponse(operation))
  140 | .then(result => {
  141 |   // we have data and can send it to back up the link chain
> 142 |   observer.next(result);
      | ^  143 |   observer.complete();
  144 |   return result;
  145 | })
View compiled
```

**Comment by skonves** [comment] 2020-10-30 16:38
A temporary workaround to manually revert back to v2.3.1:

1. Clone this repo
1. Checkout the previous release tag: `git checkout v2.3.1`
1. Install deps: `npm ci`
1. Build the extension: `npm run build`
1. Install the build output as an extension in Chrome
    1. ensure the "real" extension is uninstalled
    1. Nav to `chrome://extensions/`
    1. Switch on "Developer mode" in the top right corner
    1. Click the "Load unpacked" button in the top left corner
    1. Select the output file (it will be in the `.../shells/webextension` folder wherever you have cloned the repo)
1. Thank the dev team here for fantastic automation and a well-managed project that makes this possible 🎉

**Comment by jcreighton** [comment] 2020-10-30 16:49
Duplicate of #305

**Closed** 2020-10-30 16:49 UTC
