### ISSUE TITLE
Extension prevents websites (tested on atlassian.com) from loading styles 

### ISSUE THREAD

**Issue by Yvad60** [apollographql/apollo-client-devtools#1162] opened 2023-12-10 07:57 UTC
**Intended outcome:**
I was surfing the web trying to access the Atlassian website [atlassian.com](https://www.atlassian.com/). The website looks like the following when the extension is disabled or removed

<img width="1578" alt="Screenshot 2023-12-10 at 09 32 23" src="https://github.com/apollographql/apollo-client-devtools/assets/54445417/53ef0743-91d7-46e5-9297-bb515084dce1">

**Actual outcome:**
The website loads without styles 

<img width="1585" alt="Screenshot 2023-12-10 at 09 50 45" src="https://github.com/apollographql/apollo-client-devtools/assets/54445417/9c6ab23f-a727-4104-9390-1633ff65e03d">

**How to reproduce the issue:**
Install or enable the extension then open  [atlassian.com](https://www.atlassian.com/)

**Desktop (please complete the following information):**

- OS: macOS Sonoma 14.0
- Browser: Arc Version 1.20.1 (43987), Brave v 1.61.101, Microsoft Edge Version 120.0.2210.61
- Extension version: Version 4.2.3

**Comment by phryneas** [comment] 2023-12-11 09:57
This seems to be caused by us inserting a `<script>` tag at the end of `<head>`. Apparently, they are SSRing their `head` element as well, and get a hydration mismatch - but instead of gracefully recovering from that, they just give up. 

Seems like some custom flavor of SSR that isn't very well tested :/

We could go around this by inserting our script tag after the `body` element, inside the `html` element - I just tested that, and it works. But it's not compliant with the HTML spec.

To be honest, I'm not sure if this is something we can cater to. Browser extensions have to insert their content somewhere, and if a page completely crashes because it has an additional `<script` tag, no matter where we insert it there will always be another page crashing if we insert it somewhere else. 
I'll bring it up at our next internal meeting, but right now my gut feeling tells me that Atlassian really needs to get their homepage fixed - if it's not crashed by the Apollo DevTools, it will be crashed by a hundred other extensions - this is something extensions *need* to do to function.

**Comment by mrm007** [comment] 2023-12-14 04:23
It's not just Atlassian. 

This _custom flavour_ of SSR is quite popular in React apps, especially as React Server Components become more widely adopted. Next.js (app router) and Remix render the whole HTML document on the server.


https://github.com/apollographql/apollo-client-devtools/assets/3297808/096e63ee-ce0c-4869-a397-4f5876b4cc81

Not sure if related, but the extension crashes the Dev Tools panel in Firefox. With the extension disabled:


https://github.com/apollographql/apollo-client-devtools/assets/3297808/ddc87fa6-313d-49cb-8285-a3e16e40ab0d

**Comment by phryneas** [comment] 2023-12-14 10:15
> This custom flavour of SSR is quite popular in React apps, especially as React Server Components become more widely adopted. Next.js (app router) and Remix render the whole HTML document on the server. Also reported in https://github.com/apollographql/apollo-client-devtools/issues/937.

They *render* the whole page on the server, usually but they don't *hydrate* the whole page on the server, which is what causes the problem. 
Especially the Next.js App router will only hydrate client components, so while everything is rendered on the server, only a small part of the page's `body` is actually hydrated and can cause hydration mismatches, but not the `head` part of the application. 
As for Remix, I'll have to look into that, but as I said, for browser extensions injecting script tags into the document is a necessity, and I would image that if Remix is trying to hydrate the whole header, they will have the same problem with other extensions, and I would assume they might have changed this on their side long ago - but I'll look into it.

Also, generally, the worst thing that will happen on a hydration mismatch is that React automatically rerenders the whole page. That this doesn't happen on the Atlassian site seems very weird - they seem to have managed to disable a central part of React rendering for some reason.

> Not sure if related, but the extension crashes the Dev Tools panel in Firefox. With the extension disabled:

Honestly I don't even know how we could crash the DevTools even if we wanted as they run in isolation from our DevTools tab, but I agree, this is very weird behaviour.

**Comment by phryneas** [comment] 2023-12-14 10:22
PS: After digging a little bit, it seems like Remix is using React to render and rehydrate the *entirety* of `document`, which means there is no place in the whole website we could inject *any* extension-related script into, not even "in `html`, after `body`" or any similarly obscure places.
As a result it seems that Remix will be broken by any browser extension that needs to inject code into the website. This is really irritating.

**Comment by phryneas** [comment] 2023-12-14 10:25
It looks like there is a relatively new browser api to work around that, [`registerContentScripts`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/registerContentScripts). 
I guess I'll look into that further.

**Comment by phryneas** [comment] 2023-12-14 13:45
This should be fixed by https://github.com/apollographql/apollo-client-devtools/pull/1164

**Comment by mrm007** [comment] 2023-12-17 06:20
Thank you @phryneas 🙏

**Comment by jerelmiller** [comment] 2023-12-20 04:32
Hey @Yvad60 and @mrm007 👋 

Unfortunately we discovered an issue with our latest release and had to roll it back. I'm reopening this issue once more until we are able to dig into the changes a bit more. So sorry for this!

**Closed** 2024-02-26 22:25 UTC
