### ISSUE TITLE
Extension breaks Remix.run React framework hydration

### ISSUE THREAD

**Issue by msakrejda** [apollographql/apollo-client-devtools#937] opened 2022-11-03 17:00 UTC
When using the default Remix.run starter app, with the extension enabled, React hydration breaks. May be related to #839, but opening a new issue, since it's a little different and the reporter closed that one.

**Intended outcome:**

Use a default Remix.run template app without errors.

**Actual outcome:**

In the console, I see the errors 

```
Warning: Expected server HTML to contain a matching <head> in <html>.
head
html
App
RemixRoute@http://localhost:3000/build/_shared/chunk-RPSUDZQU.js:2531:20
Routes2@http://localhost:3000/build/_shared/chunk-RPSUDZQU.js:2515:7
Router@http://localhost:3000/build/_shared/chunk-RPSUDZQU.js:741:7
RemixCatchBoundary@http://localhost:3000/build/_shared/chunk-RPSUDZQU.js:1018:28
RemixErrorBoundary@http://localhost:3000/build/_shared/chunk-RPSUDZQU.js:944:5
RemixEntry@http://localhost:3000/build/_shared/chunk-RPSUDZQU.js:2408:20
RemixBrowser@http://localhost:3000/build/_shared/chunk-RPSUDZQU.js:3166:27 react_devtools_backend.js:4026:25
```

and

```
Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    React 12
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    js scheduler.development.js:571
    js scheduler.development.js:633
    __require chunk-IE366Y5W.js:8
    js index.js:6
    __require chunk-IE366Y5W.js:8
    React 2
    __require chunk-IE366Y5W.js:8
    js React
    __require chunk-IE366Y5W.js:8
    js React
    __require chunk-IE366Y5W.js:8
    <anonymous> entry.client.tsx:3
react-dom.development.js:12507:8
```

**How to reproduce the issue:**

```
npx create-remix@latest apollo-devtools-bug-repro
cd apollo-devtools-bug-repro
npm run dev
```

Then open the browser to http://localhost:3000/ and open the browser dev tools to see the error.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox 106.0.2
 - Extension version: 4.1.2

**Comment by alessbell** [comment] 2023-12-18 18:24
Hi @msakrejda, I can confirm this has been fixed in 4.3.0 via https://github.com/apollographql/apollo-client-devtools/pull/1164.

The Chrome extension store is already distributing the newest version and FF should update within a day or two, once you update you should no longer see this happening. Thanks for reporting it!

**Comment by jerelmiller** [comment] 2023-12-20 04:33
Hey @msakrejda 👋 

Unfortunately we discovered an issue with our latest release and had to roll it back. I'm reopening this issue once more until we are able to dig into the changes a bit more. So sorry for this!

**Comment by jerelmiller** [comment] 2024-02-21 04:43
Hey @msakrejda, I was digging into this a bit more, but I believe the issue is actually over on the Remix side. I just installed a new app per your instructions in a fresh Firefox instance running no extensions and saw the same hydration mismatch that you reported above.

<img width="1728" alt="Screenshot 2024-02-20 at 9 41 18 PM" src="https://github.com/apollographql/apollo-client-devtools/assets/565661/87842b70-534a-4447-9b41-fd0f3e4aff72">

As you can see, I have no extensions installed/running:

<img width="1728" alt="Screenshot 2024-02-20 at 9 42 11 PM" src="https://github.com/apollographql/apollo-client-devtools/assets/565661/b0386a0a-b944-43f5-86e9-d29ac37cf857">


As such, I'm going to go ahead and close this as I don't think there is anything we can do. Thanks!

**Closed by jerelmiller** 2024-02-21 04:43 UTC
