### ISSUE TITLE
Clicking on the Queries tab just results in the whole tab becoming blank

### ISSUE THREAD

**Issue by olalonde** [apollographql/apollo-client-devtools#150] opened 2018-10-31 11:05 UTC
I'm using the latest extension from the Chrome Store and when clicking on the Queries tab just results in the whole tab becoming blank...

<img width="1082" alt="screenshot 2018-10-31 19 04 45" src="https://user-images.githubusercontent.com/416585/47784214-e46fa400-dd3f-11e8-86f0-de0e763e45bf.png">

The other tabs work fine.

**Comment by hwillson** [comment] 2018-10-31 11:07
Duplicate of https://github.com/apollographql/apollo-client-devtools/issues/137 (and fixed in https://github.com/apollographql/apollo-client-devtools/pull/149). We'll get a new release out shortly.

**Closed by hwillson** 2018-10-31 11:07 UTC
