### ISSUE TITLE
Incorrect work with `extend` in Query and Mutation

### ISSUE THREAD

**Issue by VasiliKubarka** [apollographql/apollo-client-devtools#159] opened 2018-12-14 09:54 UTC
Hello all! Have few questions/bugs/features with `extend` keyword in version `2.1.5`

1) Queries declared with `extend` not seen in devtools
![image](https://user-images.githubusercontent.com/19685464/49995644-cc757c00-ff9d-11e8-90d8-a9921af7f9e7.png)
![image](https://user-images.githubusercontent.com/19685464/49995648-d1d2c680-ff9d-11e8-8213-6719c956f19e.png)

2) when locally try to extend existing queries from server, have error `Must provide schema definition with query type or a type named Query.`
can we remove this check or add functionality to work when all queries extends Query?

steps to reproduce:
1) add any endpoint to ApolloClient
2) add one type def that extends Query 
```
const typeDef = gql`
  extend type Query {
    users: [User]
  }
`;
```
result error: Must provide schema definition with query type or a type named Query.
but code is valid and works well

I can not create  `type Query` without extending because it breaks validations

Any thoughts?

**Comment by justinanastos** [comment] 2019-02-11 17:29
Thanks for opening an issue @VasiliKubarka ! Can you take a look at my comments here: https://github.com/apollographql/apollo-client-devtools/issues/132#issuecomment-462415551. Would #1 qualify as a reproduction for what you're seeing? If so, I'll mark this is a duplicate of #132. If not, can you please provide a reproduction?

Relates to #132

**Comment by VasiliKubarka** [comment] 2019-02-19 14:16
@justinanastos Hello, thanks for reply, don't think that [it's](https://github.com/apollographql/apollo-client-devtools/issues/132#issuecomment-462415551) the same behavior that I faced. 
Anyway I tested this on `2.1.8` version, and for this version both client typeDefs  with `type Query...` and `extend type Query` are not shown in **Documentation Explorer** in `Query` type.
I checked that in both [your apollo-pre branch](https://github.com/justinanastos/fullstack-tutorial/tree/justin/apollo-pre-2.5) and [alfa master branch](https://github.com/apollographql/fullstack-tutorial)

```
export const typeDefs = gql`
  extend type Query {
    isLoggedIn: Boolean!
    cartItems: [Launch]!
  }

  extend type Launch {
    isInCart: Boolean!
  }

  extend type Mutation {
    addOrRemoveFromCart(id: ID!): [Launch]
  }
`;
```
For example in both versions `isLoggedIn` and `cartItems` are not shown in queries list
![image](https://user-images.githubusercontent.com/19685464/53020995-3e1fe980-3469-11e9-974b-c76f11f0c1f0.png)

but as I described before, client typeDefs has been shown in `2.1.5` version if where written without `extend` keyword 

So can you please describe,  what is expected behavior for reflection client typeDefs in devTools?

**Comment by justinanastos** [comment] 2019-02-26 20:45
We've added all local state to GraphiQL with [v2.2.0](https://github.com/apollographql/apollo-client-devtools/releases/tag/v2.2.0). This works for `apollo-client`/`react-apollo` v2.4 and v2.5 that was released today!

**Comment by raedle** [comment] 2019-02-27 11:59
I've updated to v2.2.0 and it does not show the local schema (using it together with apollo-client@2.5.0).

Can anyone confirm that the local schema shows up in the Documentation Explorer in v2.2.0?

**Comment by justinanastos** [comment] 2019-02-27 16:49
Can you give any more details @raedle ? I checked out the [full stack tutorial](https://github.com/apollographql/fullstack-tutorial), ran the apps in [`final/client`](https://github.com/apollographql/fullstack-tutorial/tree/master/final/client) and [`final/server`](https://github.com/apollographql/fullstack-tutorial/tree/master/final/server). Note the `typeDefs` definition:

https://github.com/apollographql/fullstack-tutorial/blob/014d900d62265a1c69825cb82367b2e838e05f2a/final/client/src/resolvers.js#L4-L17

I see the local schema extensions in the Documentation Explorer and there are no warnings given about either the local fields or the `@client` directive in the query input panel.

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/5224118/53507317-aaac7100-3a85-11e9-88fa-24cabd06f55f.png">

**Comment by raedle** [comment] 2019-02-27 18:37
Thanks @justinanastos for your quick response. I tried the fullstack tutorial, but even with this one I don't see the local schema in the Documentation Explorer.

I even installed the Apollo Client Dev Tools extension on a clean Google Chrome account, but still no local schema.

<img width="1792" alt="apollo-client-dev-tools" src="https://user-images.githubusercontent.com/489051/53513834-802ed800-3ac6-11e9-835c-9191d50983e2.png">

I'm using Google Chrome Version 72.0.3626.119 and the Apollo Client Dev Tools v2.2.0 from the Google Marketplace.

**Comment by justinanastos** [comment] 2019-02-27 19:21
@raedle Are you on the latest version of the fullstack tutorial with the latest dependencies installed in `final/client` and `final/server`?

To check:

```
cd final/client
npm ls apollo-client react-apollo
```

```
$ cd final/client
$ npm ls apollo-client react-apollo
client@0.1.0 xxx/fullstack-tutorial/final/client
├── apollo-client@2.5.1
└── react-apollo@2.5.1
```

What do you see?

**Comment by raedle** [comment] 2019-02-27 19:55
It works after updating both packages to v2.5.1.

In my own project, I had both packages at v2.5.0, and the fullstack was on apollo-client@2.5.0-alpha.10 and react-apollo@2.4.0-alpha.3.

Thanks you!

**Comment by justinanastos** [comment] 2019-02-27 20:48
Thank you @raedle ! There was a change going from rc2 → rc3 that changed how the Apollo Client DevTools access Apollo Client's local `typeDefs`. That explains why it didn't work with the alpha versions! Thanks for following up and letting me know things are working now!

**Closed by justinanastos** 2019-02-27 20:48 UTC
Labels: bug, needs-reproduction
