### ISSUE TITLE
Cache data in Dev tool does not refresh automatically. [dev tool should be stable and effective]

### ISSUE THREAD

**Issue by KevinYaoooooo** [apollographql/apollo-client-devtools#164] opened 2019-01-09 05:56 UTC
Cache data in Dev tool does not refresh automatically

After I modify the response data manually, the data in dev tool cache is not the latest one.

but the query data result in code is the latest one.

After I reopen the Dev  tool again, the cache shows the right data.

This is really confusing, the dev tool is very unstable, could you please solve this issue? the dev tool is kinda important for Developers, good dev tool could improve the productivity a lot for developers.

Thanks!

**Comment by jure** [comment] 2019-01-15 22:38
You could try the version from the repository, it works a bit better for me, although it's still a bit unpredictable.

**Comment by KevinYaoooooo** [comment] 2019-01-16 01:04
@jure thanks, I will give it a try, but still, if the one in repository is more stable, why it doesn't publish to chrome store

**Comment by justinanastos** [comment] 2019-02-11 17:59
Thanks for posting this issue and thank you for your patience. We totally understand that the devtool is important to developers because we use it internally. This is a duplicate of https://github.com/apollographql/apollo-client-devtools/issues/108 so I'm going to close _this_ ticket. At the time of this writing there are 34 👍 on that issue (including my own!). Please follow the progress over there.

I'm going to be working on this very soon.

**Closed by justinanastos** 2019-02-11 17:59 UTC
Labels: duplicate
