### ISSUE TITLE
Stop working after latest release

### ISSUE THREAD

**Issue by joanabeats** [apollographql/apollo-client-devtools#266] opened 2020-05-29 10:59 UTC
Hi guys, apollo client devtools is not working correctly after the latest release, it crashes after trying to access the 'cache' tab, the cache doesn't open and the application freezes showing a black screen. 
I'm using apollo v2

Great app btw :D

**Comment by eDubrovsky** [comment] 2020-05-29 11:01
Same problem with Apollo v3

**Comment by hwillson** [comment] 2020-05-29 12:21
Thanks all - are you using Chrome or Firefox? And can you confirm the version is 2.3.0?

**Comment by withinboredom** [comment] 2020-05-29 13:25
In my case with 2.3.0 and Apollo v3, I get the black screen on Queries tab while the cache works fine.

**Comment by joanabeats** [comment] 2020-05-29 13:28
Yes, version 2.3.0 and I'm using chrome v83

**Comment by hwillson** [comment] 2020-05-29 13:38
Is there any chance someone here someone could provide a small runnable reproduction that breaks devtools? That would definitely help speed up troubleshooting.

**Comment by hinok** [comment] 2020-05-29 18:53
It stopped working in my app

```js
├── @apollo/react-hoc@3.1.3
├── @apollo/react-hooks@3.1.3
├── @apollo/react-ssr@3.1.3
├── apollo-cache@1.3.4
├── apollo-cache-inmemory@1.6.5
├── apollo-client@2.6.8
├── apollo-link@1.2.13
├── apollo-link-batch-http@1.2.13
├── apollo-link-error@1.1.12
├── apollo-upload-client@12.1.0
├── apollo-utilities@1.3.3
```

and newest chrome.

Demo: https://ovgwz.csb.app/
https://codesandbox.io/s/react-apollo-with-hooks-ovgwz?file=/src/index.js

**Comment by jcreighton** [comment] 2020-05-29 18:59
@hinok Many thanks for adding the demo! When I view it using `2.3.0`, the DevTools appear to be working. Could you describe what issues you're seeing?

**Comment by jcreighton** [comment] 2020-05-29 19:03
Below is what I'm seeing. If you are able to record what's happening, that will be helpful!
![apollodevtools](https://user-images.githubusercontent.com/5232812/83295773-8924c280-a1bd-11ea-832b-d7464319df68.gif)

**Comment by hinok** [comment] 2020-05-29 19:09
@jcreighton 

![demo](https://user-images.githubusercontent.com/1313605/83296101-6e1f7600-a1f0-11ea-9d06-95bb9c35367d.gif)

In my application I always get crash after clicking the "Cache" tab. On the video above you can see that sometimes it works, sometimes not.

**Comment by jcreighton** [comment] 2020-05-29 19:12
@hinok Super helpful! I'll keep digging around see if I can get this reproduced on my side.

**Comment by eDubrovsky** [comment] 2020-05-29 19:17
> @jcreighton
> 
> ![demo](https://user-images.githubusercontent.com/1313605/83296101-6e1f7600-a1f0-11ea-9d06-95bb9c35367d.gif)
> 
> In my application I always get crash after clicking the "Cache" tab. On the video above you can see that sometimes it works, sometimes not.

the same problem on macOS and Chrome Version 83.0.4103.61

**Comment by hinok** [comment] 2020-05-29 19:23
@jcreighton This is what I captured from the devtools devtools 💥 

After clicking on **Cache**

<img width="832" alt="Zrzut ekranu 2020-05-29 o 21 20 48" src="https://user-images.githubusercontent.com/1313605/83297245-82fd0900-a1f2-11ea-9bac-49064876f057.png">

<img width="1440" alt="Zrzut ekranu 2020-05-29 o 21 21 25" src="https://user-images.githubusercontent.com/1313605/83297266-8b554400-a1f2-11ea-9c5d-f1671ca17162.png">

**Comment by jcreighton** [comment] 2020-05-29 19:26
@hinok I saw that! Seems there some sort of race condition where value is set to

**Comment by jcreighton** [comment] 2020-05-29 19:27
Ugh, I didn't mean to close the issue. Hit something with my wrist... 😆

**Comment by jcreighton** [comment] 2020-05-29 19:29
@eDubrovsky Are you able to build the extension and check as well?

**Comment by jcreighton** [comment] 2020-05-29 19:39
@joanabeats If you are able to check the related PR and let me know if it fixes the issue, that would be great!

**Comment by hinok** [comment] 2020-05-29 19:43
Now it works 🥳

but... I think that we have another issue? I've never seen `__schema` in the cache panel. After clicking Cache, I need to wait 5-10s and finally get the view with `__schema` that contains a lot of things that shouldn't be the cache.

On the first view, after refreshing the page everything looks good.
When I navigate to another page (new graphql queries are run), the devtools panel is frozen... seems that it's broken but after 5-10s it contains `__schema`.

![schema-in-query](https://user-images.githubusercontent.com/1313605/83298801-5f878d80-a1f5-11ea-8dc9-d47c5af9d99c.gif)

**Comment by jcreighton** [comment] 2020-05-29 19:47
@hinok Thanks for checking out the PR and so happy it fixes the issue! 

As for the `__schema` issue, that's working correctly. But there's an older opened PR to remove it (https://github.com/apollographql/apollo-client-devtools/pull/235). I'm newer to the project so I need some time to figure out the history of this and if we want to make that change (or why we wouldn't.)

**Closed** 2020-05-29 19:50 UTC

**Comment by jcreighton** [comment] 2020-05-29 19:55
@joanabeats I've closed this for now and I'm working to get a `2.3.1` release out. If that doesn't solve the issue, we'll reopen this!

**Comment by joanabeats** [comment] 2020-05-29 21:13
@jcreighton   I tested the PR, and is still crashing, it freezes a lot when opening the cache tab, I don't see the black screen, but keeps freezing a lot now.

**Comment by jcreighton** [comment] 2020-05-29 21:49
@joanabeats Ok, thank you for testing it out! I'm unable to reproduce what you're seeing so if you could create a runnable sample, that would be ideal. You can also inspect the DevTools themselves and see if there's an error in the console.

**Comment by ebrearley** [comment] 2020-05-30 23:10
I'm not sure if this will help (probably wont because others have done the same), but just in case - here's a recording of the devtool's console while it crashes:

![apollo-typename-crash](https://user-images.githubusercontent.com/10335665/83340655-2d257f80-a31e-11ea-8777-37dda335290f.gif)

Also, a couple times it seemed to get into an infinite loop with thousands of the same error, before crashing. Couldn't consistently reproduce to get a recording, just thought it's worth mentioning.

**Comment by joanabeats** [comment] 2020-06-01 09:40
@jcreighton I test it again, it freezes mostly on cache tab, may be related with the new content that appears on the cache '__schema', and I also got this on the console : 

`VM1353:1 Uncaught TypeError: Cannot redefine property: __APOLLO_DEVTOOLS_GLOBAL_HOOK__
    at Function.defineProperty (<anonymous>)
    at <anonymous>:1:555
    at <anonymous>:1:960`

Tks.

**Comment by jcreighton** [comment] 2020-06-01 14:27
@joanabeats I've opened up a separate issue to track this since it's unrelated to the initial problem here.

**Comment by jcreighton** [comment] 2020-06-02 00:57
@joanabeats @hinok There's a PR related to #271 if you'd like to check it out.
