### ISSUE TITLE
Dev Tools stop tracking queries and cache once it does an IntrospectionQuery

### ISSUE THREAD

**Issue by jaydlawrence** [apollographql/apollo-client-devtools#334] opened 2020-12-21 20:53 UTC
**Intended outcome:**
Use the dev tools to track new queries and cache changes

**Actual outcome:**
Dev tools only seem to be able to track queries and changes to cache before it does its first IntrospectionQuery request. Once that comes back, it won't track anything else.

**How to reproduce the issue:**
My colleague @jasondippel and I have created a small repo based off of the apollo client and server examples.
https://github.com/jaydlawrence/apollo-auth0-sample/tree/no-auth0

The `no-auth0` branch is stripped down and shows the issue.

Start the client and server, visit the client with Apollo Dev Tools open.
You can see the publicQuery show up in the dev tools as well as the record in the cache.

Clicking the "Run public query" button will rerun that query and it doesn't show up in the dev tools, but it can be seen in the network tab.

Also, clicking the second button, "Show Second Component", will render a second component which will do a second unrelated query. This query also shows up in the network tab, but does not show up in the dev tools; neither in the queries section, nor in the cache.

After much debugging, it seems like whichever queries get in before the IntrospectionQuery request seem to show up and anything after that does not.

Here is a video to demonstrate it.
https://user-images.githubusercontent.com/1242060/102821151-f774e080-43ac-11eb-9d4e-a0ff9fd666a5.mov

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser Chrome
 - Browser version 87
 - Extension version 2.3.5

Also tried on Firefox 84 and it has the same issue.

**Comment by jcreighton** [comment] 2021-01-05 17:57
Thanks for the reproduction & thorough issue ticket @jaydlawrence! I am seeing the issue with 2.3.5. We're working on a major release (3.0) and I've also confirmed this isn't an issue with that release. We're focused on getting 3.0 out of the door so I'm unsure if we'll get a fix in for 2.3 but this is super helpful. Would love for you to check out [3.0](https://github.com/apollographql/apollo-client-devtools/tree/release-3.0) - still a work in progress but the more users we have test it out, the more issues we can fix!

**Comment by jaydlawrence** [comment] 2021-01-05 18:34
Thanks. That makes sense. Will will try it out for our project.

**Comment by hwillson** [comment] 2021-02-01 15:10
Since this has been resolved in 3.0 (which is going to be published soon), I'll close this off. Thanks!

**Closed by hwillson** 2021-02-01 15:10 UTC
Labels: :rose: has-reproduction
