### ISSUE TITLE
not show any data

### ISSUE THREAD

**Issue by zhnd** [apollographql/apollo-client-devtools#1316] opened 2024-04-05 14:31 UTC
### `@apollo/client` version
@apollo/client 3.9.10

### Apollo Client Devtools version
4.11.2

use this dev tool with chrome not show any data, But firfox is perfectly fine

- chrome
<img width="1081" alt="image" src="https://github.com/apollographql/apollo-client-devtools/assets/24654957/2d57f876-7999-4cf2-ae0f-9d03d103ea83">

- firefox
<img width="1332" alt="image" src="https://github.com/apollographql/apollo-client-devtools/assets/24654957/350473a3-af45-4842-9b40-80df1ec02874">

**Comment by jerelmiller** [comment] 2024-04-05 14:33
@zhnd thanks for the report! Thats very interesting!

By chance do you have an app I can run this against? Chrome works well with our development app so perhaps there is something else at play here.

**Comment by zhnd** [comment] 2024-04-05 14:44
> @zhnd thanks for the report! Thats very interesting!
> 
> By chance do you have an app I can run this against? Chrome works well with our development app so perhaps there is something else at play here.

I don't know why, I disabled all the plug-ins and looked normal after restarting chrome.

**Comment by jerelmiller** [comment] 2024-04-05 14:48
Hmmm we've seen that reported a couple times (https://github.com/apollographql/apollo-client-devtools/issues/1244#issuecomment-2019380737 for example). I'll keep investigating this to try and nail down the cause. Glad the restart fixed it though super frustrating that you need to do so in the first place! I'll add this to https://github.com/apollographql/apollo-client-devtools/issues/1247 where I'm recording instances of this happening 🙂

**Comment by jerelmiller** [comment] 2024-06-06 17:54
Hey @zhnd 👋 

We've done quite a bit of work lately to stabilize the messaging between the content scripts and devtools. I used to be able to frequently reproduce this behavior, but I believe this has now been fixed in a recent release as I have been unable to reproduce. As such, I'm going to go ahead and close this issue as resolved. Please let me know if you're still seeing this after upgrading to a recent version and I'd be happy to reopen this issue. Thanks!

**Closed by jerelmiller** 2024-06-06 17:54 UTC
Labels: 🐞 bug
