### ISSUE TITLE
Incompatible with Chrome dark theme

### ISSUE THREAD

**Issue by akoutmos** [apollographql/apollo-client-devtools#48] opened 2017-06-21 23:23 UTC
When using the dark theme for Chrome dev tools, the extension fails to render properly. Confused me at first as I thought none of my queries were showing up in the list, but it turns out that the text was rendering as white against a white background.

**Comment by Draccoz** [comment] 2017-06-22 08:08
Same thing here. This is pretty annoying, as I cannot see any active queries or store contents without highlighting the text (`ctrl + a`). Here are some screens:
![image](https://user-images.githubusercontent.com/4731061/27423574-6c2a7cc0-5732-11e7-9eda-1ef7ab4aad71.png)
![image](https://user-images.githubusercontent.com/4731061/27423584-75c125ea-5732-11e7-9573-18de52b9e9dc.png)
![image](https://user-images.githubusercontent.com/4731061/27423605-83964196-5732-11e7-8eb9-f7b3374f325f.png)
![image](https://user-images.githubusercontent.com/4731061/27423609-88c33fb6-5732-11e7-86ef-fb831d2f2d35.png)
![image](https://user-images.githubusercontent.com/4731061/27423632-9500b7ea-5732-11e7-9c7e-b686f2fa2f3b.png)
![image](https://user-images.githubusercontent.com/4731061/27423660-a3738c30-5732-11e7-986b-50f6ca9d27ad.png)

**Comment by rrdelaney** [comment] 2017-06-22 16:12
Should be some CSS - I'll look into this 💯

**Comment by stubailo** [comment] 2017-06-23 05:36
That's odd! We recently had a PR adding dark theme support: https://github.com/apollographql/apollo-client-devtools/pull/14

I wonder if we broke it somehow.

**Comment by stubailo** [comment] 2017-06-23 05:38
Oh - @rrdelaney I bet the PR for adding a white background for Firefox added a white background for Chrome dark mode as well. Before the background was transparent, and ended up being dark by default. So it looks like the CSS for making the text light is working as intended :]

Basically we just need to look at everywhere `white` was added here: https://github.com/apollographql/apollo-client-devtools/pull/41/files

And then add a special case if it's inside a `.dark` class.

**Comment by rrdelaney** [comment] 2017-06-29 02:16
Fixed by #52

**Closed by rrdelaney** 2017-06-29 02:16 UTC
Labels: bug, help wanted

**Comment by Draccoz** [comment] 2017-06-29 11:42
When can we see it live?

**Comment by rrdelaney** [comment] 2017-06-29 17:38
A release was just pushed to the Chrome Webstore, should be live within the hour!

**Comment by Draccoz** [comment] 2017-06-30 08:48
Works like a charm, thanks for quick respond!
