### ISSUE TITLE
In query editor, cursor is black on dark grey, making it difficult to see.

### ISSUE THREAD

**Issue by DanielPower** [apollographql/apollo-client-devtools#550] opened 2021-05-06 15:42 UTC
**Intended outcome:**
Cursor should be white

**Actual outcome:**
Cursor is black

![Screen Shot 2021-05-06 at 1 10 29 PM](https://user-images.githubusercontent.com/12166320/117326675-78b8a580-ae6c-11eb-9d76-60c9d2cec9ec.jpg)

**How to reproduce the issue:**
Open dev tools, look at the cursor. I'm not sure if this is related to the MacOS System dark theme, or if it would occur on other operating systems as well. I've tested in both Firefox and Brave, with the same results.

In Brave, I have also tried switching the dev tools to light mode. But Apollo Dev Tools seem to ignore this setting and continues to have a dark theme with a black cursor.

**Desktop (please complete the following information):**
 - OS: MacOS 11.13.1 with Dark Mode enabled
 - Browser: Brave 1.23.75, Firefox Developer Edition 89.0b8
 - Extension version: 3.0.5

**Comment by elainemckinley** [comment] 2021-05-14 18:27
Heavily agree here, this is driving me nuts :P 

Looks like this might be a regression also: https://github.com/apollographql/apollo-client-devtools/issues/130

**Comment by jpvajda** [comment] 2022-05-17 19:23
We've now better integrated the query editor with [Apollo Studio](https://www.apollographql.com/docs/studio/) so this issue doesn't seem relevant now, I'll close it out, but thanks for bringing this to our attention.

**Closed** 2022-05-17 19:23 UTC
