### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by stereobooster** [apollographql/apollo-client-devtools#168] opened 2019-01-21 09:02 UTC
As soon as I switch to cache tab in Apollo extension I see white screen and this trace in console
```
devtools.js:1 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at t.value (devtools.js:1)
    at t.value (devtools.js:1)
    at t.value (devtools.js:1)
    at u (devtools.js:1)
    at beginWork (devtools.js:1)
    at r (devtools.js:1)
    at o (devtools.js:1)
    at a (devtools.js:1)
    at k (devtools.js:1)
```

Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by justinanastos** [comment] 2019-02-11 20:53
Thanks for the bug report @stereobooster ! This appears to be a duplicate of https://github.com/apollographql/apollo-client-devtools/issues/168. I asked a question (just today!, https://github.com/apollographql/apollo-client-devtools/issues/107#issuecomment-462426867) asking for help with a reproduction. I showed two repos that this _doesn't_ happen for. I'd very much appreciate if you could post a minimal reproduction on that ticket!

**Closed by justinanastos** 2019-02-11 20:53 UTC
Labels: duplicate
